# Generated by Django 5.2.1 on 2025-05-23 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resumefeedback',
            name='feedback',
            field=models.TextField(blank=True),
        ),
    ]
