# Generated by Django 5.2.1 on 2025-06-24 00:26

import config.utils.file_size_restriction
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CorrectedResume',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('original_resume', models.FileField(upload_to='media/', validators=[config.utils.file_size_restriction.validate_file_size])),
                ('corrected_resume_text', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='correctedresumes', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
