# Generated by Django 5.2.1 on 2025-05-25 21:31

import config.utils.file_size_restriction
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0002_alter_resumefeedback_feedback'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resumefeedback',
            name='resume_file',
            field=models.FileField(upload_to='media/', validators=[config.utils.file_size_restriction.validate_file_size]),
        ),
    ]
